version: "3.8"

services:
  app:
    image: ghcr.io/YOUR_GITHUB_USERNAME/stella-pet-services:latest
    container_name: stella-app
    network_mode: host
    env_file:
      - .env
    restart: always
